// Generates a boilerplate repository with the given title, for the given Github username, and generated by the given CLI command
export const generateBoilerplate = async (
  title: String,
  username: String,
  command: String
) => {
  try {
    const requestBody = {
      projectTitle: title,
      githubUsername: username,
      cliCommand: command,
    };
    const response = await fetch("/api/generate-boilerplate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
    });

    if (response.ok) {
      const data = await response.json();
      console.log(
        "Boilerplate generated! Response from /api/generate-boilerplate: ",
        data
      );
    } else {
      const errorData = await response.json();
      console.error("Failed to generate boilerplate.", errorData);
    }
  } catch (error) {
    console.error("Error generating boilerplate.", error);
  }
};
